### ISSUE TITLE
Examples fail to start on current nightly in release

### ISSUE THREAD

**Issue by linkmauve** [rust-wii/luma#14]
When I run e.g. the `vi-draw` example in Dolphin, the `_start` function doesn’t even reach `main`, it seems to do a `rfi` in loop instead when returning from `memset`.

**Comment by FrictionlessPortals** [comment]
I'm currently on ``rustc 1.64.0-nightly (06754d885 2022-07-08)`` and the vi-draw example seems to get past ``memset``, which nightly version did it fail with? I'll try to test it again and try it with the old ``memset`` implementation

**Comment by CyrusAlbright** [comment]
I ran the latest main branch `vi_draw` example in Dolphin as well (with `rustc 1.64.0-nightly (c396bb3b8 2022-07-10)`):
- In release it halts with a black screen. I don't even get to see a stack trace. I'm not terribly familiar with PowerPC assembly but looking through the generated assembly I don't see an `rfi` instruction in any of the called functions leading up to `main` including in `memset`, but maybe I missed it? In any case I don't know exactly what's wrong.
- In debug it shows a white screen and gets caught in a panic in `paint_pixels()`, presumably an arithmetic overflow because that's the only source of panics I see there.

I don't know why it would be able to reach `paint_pixels()` in debug and not release, but maybe this can be helpful.

**Comment by CyrusAlbright** [comment]
Addendum: I set `overflow-checks = false` in the debug profile and it works seamlessly.

**Comment by linkmauve** [comment]
In Dolphin when you enable the console, you can see it panic since 7d2fe67f7edd277c879f00f49997ce3a04b08958:
```
44:35:673 Core/HLE/HLE_OS.cpp:84 N[OSREPORT_HLE]: 80005d2c->80005d20| panicked at 'attempt to subtract with overflow', src/bin/vi-draw.rs:55:18
```

I have a fix which doesn’t require overflow-checks (I wrongly translated `int` to `u32` instead of `i32` from weston-simple-shm), but this still doesn’t fix the release build so I’ll keep this issue open.

**Comment by linkmauve** [comment]
Alright, after some more investigation, the issue isn’t `memset` per se, it’s that Rust stuff use the `__stack_addr`/`__stack_end` symbols defined in linker.ld, while crt0.S uses `__crt0stack`/`__crt0stack_end` instead, which is right in `.bss`, which we clear right away in this same `memset()` call, and loads back the return address as `0` thus `blr` to `NULL`.  I have a fix incoming. :)
